---
  - name: Installing requirements
    hosts: localhost
    connection: local
    become: yes

    tasks:

      - name: Exiting if we are not running Ubuntu
        ansible.builtin.fail:
          msg: "The OS is {{ ansible_facts['distribution'] }}. This playbook is only meant to work with Ubuntu."
        when: ansible_facts['distribution'] != "Ubuntu"

      - name: Updating system
        ansible.builtin.apt:
          update_cache: yes
          upgrade: full
        tags: update

      - name: Installing packages
        ansible.builtin.apt:
          cache_valid_time: 600
          update_cache: yes
          install_recommends: yes
          name:
            - cmake
            - build-essential
            # Fortran
            - gfortran
            # COBOL
            - gnucobol
            # Lisp
            - clisp
            # BASIC
            - vice
            - subversion
            - autoconf
            - automake
            - build-essential
            - byacc
            - flex
            - xa65
            - libgtk-3-dev
            - dos2unix
            - libpulse-dev
            - libasound2-dev
            - libglew-dev
            - libgif-dev
            - libpcap-dev
            # Pascal
            - dosbox
            - unzip
            - tofrodos
          state: latest
        tags: install

      - name: Cleaning the local apt cache
        ansible.builtin.apt:
          autoclean: yes

  - name: Setting up the environment for the current user
    hosts: localhost
    connection: local

    tasks:

      - name: Creating directories for day_04 and day_05
        ansible.builtin.file:
          path: '{{ item }}'
          state: directory
          mode: u=rwx,g=rx,o=rx
        with_items:
          - ./day_04/build/vice
          - ./day_04/build/disk
          - ./day_05/build

      - name: Checking out the subversion repository of VICE
        ansible.builtin.subversion:
          repo: https://svn.code.sf.net/p/vice-emu/code/tags/v3.7.1/vice/
          dest: ./day_04/build/vice
          in_place: yes
          force: yes

      - name: Configuring VICE
        ansible.builtin.shell:
          cmd: export enable_pdf_docs=no && cd ./day_04/build/vice/ && ./autogen.sh && ./configure --enable-gtk3ui --disable-html-docs
          creates: ./day_04/build/vice/Makefile
          executable: /bin/bash
        register: VICE_CONFIG_OUTPUT

      - name: Getting stats of ./day_04/build/vice/src/x64sc
        ansible.builtin.stat:
          path: ./day_04/build/vice/src/x64sc
        register: STAT_X64

      - name: Building VICE
        community.general.make:
          chdir: ./day_04/build/vice
        when: VICE_CONFIG_OUTPUT['changed'] or not STAT_X64['stat']['exists']

      - name: Downloading Turbo Pascal 5.5
        ansible.builtin.get_url:
          url: https://altd.embarcadero.com/download/museum/tp55.zip
          dest: ./day_05/build
          mode: u=rw,g=,o=
          checksum: sha256:a04ff65555f88cd7714a11362c6f625f254932679ad5623b207015893ef638b6
